### PR TITLE
BUG: Fix an issue with missing features

### LINKED ISSUE #250: Check that a tip exists in the BIOM table before triggering the visibleCallback to show present samples in Emperor
One of the funky issues @ElDeveloper and I ran into today that is delaying a release.

### PR DESCRIPTION
**Pull request by ElDeveloper**
Missing features in a tandem plot shouldn't be shown

Fixes #250

### CODE REVIEW

File: empress/support_files/js/select-node-menu.js [hunk 1]
```diff
@@ -402,6 +402,27 @@ define(["underscore", "util"], function (_, util) {
         }
     };
 
+    /**
+     * Warn the user when a tip or tips are not present in the feature table
+     * and ordination
+     *
+     * @return {Array} the features represented in the dataset.
+     */
+    SelectedNodeMenu.prototype._checkTips = function (tips) {
```
Comment (fedarko) [inline empress/support_files/js/select-node-menu.js:411]: Minor, but i'd suggest renaming this function so that it's clearer that it does stuff besides just validation. Maybe `_checkAndFilterTips()` or something? Up to you, though.

File: empress/support_files/js/select-node-menu.js [hunk 2]
```diff
@@ -402,6 +402,27 @@ define(["underscore", "util"], function (_, util) {
...
+        // find the tips that can be used in the UI
+        var tipsForTable = _.intersection(this.empress._biom.getObsIDs(), tips);
```
Comment (fedarko) [inline empress/support_files/js/select-node-menu.js:413]: Actually, hm. I think a more sustainable solution to this is making a new function in the BIOM table JS that takes in a list of tip IDs and returns the intersection and difference of those with `this._fIDs`. There are two advantages of this:

1. No need to worry about the array copying thing I mentioned above, since the user doesn't interact with any of the BIOM private things directly
2. We can test that the intersection / difference functionality works without having to test the `select-node-menu` class. (I know that this code is really just using underscore functions so of course it'll work right now, but it's still more complex functionality that I'd prefer to have covered by some tests if possible. Also, if underscore's API would break due to a version update or something, having this tested would be good.)

File: empress/support_files/js/biom-table.js [hunk 3]
```diff
@@ -199,6 +199,15 @@ define(["underscore", "util"], function (_, util) {
         return _.indexOf(arr, num, true) >= 0;
     };
 
+    /**
+     * Return a set of observation ids
+     *
+     * @return {Array} A set of feature identifiers.
+     */
+    BIOMTable.prototype.getObsIDs = function () {
+        return this._fIDs;
```
[the remark this answers is not in the document]
Comment (ElDeveloper) [reply empress/support_files/js/biom-table.js:208]: Very worth while, good catch!

File: empress/support_files/js/select-node-menu.js (hunk 2 above)
Comment (ElDeveloper) [reply empress/support_files/js/select-node-menu.js]: Donezo!

**Comment by ElDeveloper** [comment]
@fedarko, should be addressed now!

File: Makefile [hunk 4]
```diff
@@ -55,4 +55,5 @@ docs:
 		--m-sample-metadata-file docs/moving-pictures/sample_metadata.tsv \
 		--m-feature-metadata-file docs/moving-pictures/taxonomy.qza \
 		--o-visualization docs/moving-pictures/empress-tree-tandem.qzv \
+		--p-no-filter-unobserved-features-from-phylogeny \
```
Comment (fedarko) [inline Makefile:58]: Is this intentionally included, or was it just as a partial fix for #248?

File: tests/test-biom-table.js [hunk 5]
```diff
@@ -277,6 +277,41 @@ require(['jquery','BiomTable'], function($, BiomTable) {
...
+            var obs;
+            var oids = ['o1', 'o2', 'o3', 'o4', 'o5', 'o6', 'o7', 'o8', 'o9',
+                        'o10'];
+            obs = this.biomTable.getObsIDsIntersection(oids);
+            assert.deepEqual(obs, oids);
+
+            obs = this.biomTable.getObsIDsIntersection(['o1']);
+            assert.deepEqual(obs, ['o1']);
+
+            obs = this.biomTable.getObsIDsIntersection(['oh no']);
```
Comment (fedarko) [inline tests/test-biom-table.js:290]: :)

File: empress/support_files/js/select-node-menu.js [hunk 6]
```diff
@@ -366,8 +366,10 @@ define(["underscore", "util"], function (_, util) {
                 }
             }
 
-            // retrive the sample data for the tips
-            var samples = emp._biom.getSamplesByObservations(tips);
+            // retrive the sample data for the tips in the table
```
Comment (fedarko) [inline empress/support_files/js/select-node-menu.js:369]:
```suggestion
            // retrieve the sample data for the tips in the table
```

File: empress/support_files/js/select-node-menu.js [hunk 7]
```diff
@@ -402,6 +404,31 @@ define(["underscore", "util"], function (_, util) {
         }
     };
 
+    /**
+     * Warn the user when a tip or tips are not present in the feature table
+     * and ordination
```
Comment (fedarko) [inline empress/support_files/js/select-node-menu.js:409]:
```suggestion
     * Given an array of tip names, warns the user about those that are not
     * present in the BIOM table (using a toast message) and returns just the
     * tip names in the array that are present as features in the table.
```

File: empress/support_files/js/select-node-menu.js [hunk 8]
```diff
@@ -402,6 +404,31 @@ define(["underscore", "util"], function (_, util) {
...
+     *
+     * @return {Array} the features represented in the dataset.
```
Comment (fedarko) [inline empress/support_files/js/select-node-menu.js:411]:
```suggestion
     * @return {Array} the tip names that are also represented in the table.
```

File: empress/support_files/js/biom-table.js [hunk 9]
```diff
@@ -199,6 +199,30 @@ define(["underscore", "util"], function (_, util) {
...
+        return _.intersection(this._fIDs, other);
+    };
+
+    /**
+     * Return the feature ids in the inputed list but not in the BIOM table.
+     *
+     * @param {Array[String]} other Array of strings to compute the
+     *                              set-difference against.
+     * @return {Array[String]} feature ids in the inputed list but not in the
+     * BIOM table.
```
Comment (fedarko) [inline empress/support_files/js/biom-table.js:220]:
```suggestion
     * @return {Array[String]} feature IDs in the input array but not in the
     *                         BIOM table.
```

File: empress/support_files/js/biom-table.js [hunk 10]
```diff
@@ -199,6 +199,30 @@ define(["underscore", "util"], function (_, util) {
         return _.indexOf(arr, num, true) >= 0;
     };
 
+    /**
+     * Return the feature ids in the BIOM table and inputed list
```
Comment (fedarko) [inline empress/support_files/js/biom-table.js:203]:
```suggestion
     * Return the feature IDs shared by the BIOM table and input array
```

File: empress/support_files/js/biom-table.js [hunk 11]
```diff
@@ -199,6 +199,30 @@ define(["underscore", "util"], function (_, util) {
...
+     *
+     * @param {Array[String]} other Array of strings to compute the
+     *                              intersection against.
+     * @return {Array[String]} feature ids in the BIOM table and the inputed
+     * list.
```
Comment (fedarko) [inline empress/support_files/js/biom-table.js:208]:
```suggestion
     * @return {Array[String]} feature IDs shared by the BIOM table and other.
```

File: empress/support_files/js/biom-table.js [hunk 12]
```diff
@@ -199,6 +199,30 @@ define(["underscore", "util"], function (_, util) {
...
+     */
+    BIOMTable.prototype.getObsIDsIntersection = function (other) {
+        return _.intersection(this._fIDs, other);
+    };
+
+    /**
+     * Return the feature ids in the inputed list but not in the BIOM table.
```
Comment (fedarko) [inline empress/support_files/js/biom-table.js:215]:
```suggestion
     * Return the feature IDs in the input array but not in the BIOM table.
```

File: Makefile (hunk 4 above)
Comment (ElDeveloper) [reply Makefile:58]: Unintentional - good catch!

Comment (ElDeveloper) [inline Makefile:58]:
```suggestion
```

**Comment by ElDeveloper** [comment]
All addressed, thanks @fedarko!

**Comment by fedarko** [comment]
Sweet, thanks @ElDeveloper!
